const groupCategory = [
  "age",
  "alone",
  "amazing",
  "anger",
  "architecture",
  "art",
  "attitude",
  "beauty",
  "best",
  "birthday",
  "business",
  "car",
  "change",
  "communications",
  "computers",
  "cool",
  "courage",
  "dad",
  "dating",
  "death",
  "design",
  "dreams",
  "education",
  "environmental",
  "equality",
  "experience",
  "failure",
  "faith",
  "family",
  "famous",
  "fear",
  "fitness",
  "food",
  "forgiveness",
  "freedom",
  "friendship",
  "funny",
  "future",
  "god",
  "good",
  "government",
  "graduation",
  "great",
  "happiness",
  "health",
  "history",
  "home",
  "hope",
  "humor",
  "imagination",
  "inspirational",
  "intelligence",
  "jealousy",
  "knowledge",
  "leadership",
  "learning",
  "legal",
  "life",
  "love",
  "marriage",
  "medical",
  "men",
  "mom",
  "money",
  "morning",
  "movies",
  "success",
  "sports",
  "politics",
  "technology",
  "trust",
  "truth",
  "wisdom",
  "work",
  "women",
];

export const useRandomCategory = () => {
  return groupCategory[Math.floor(Math.random() * groupCategory.length)];
};

export const categoryData = [
  { key: crypto.randomUUID(), category: "History" },
  { key: crypto.randomUUID(), category: "Technology" },
  { key: crypto.randomUUID(), category: "Life" },
  { key: crypto.randomUUID(), category: "Death" },
  { key: crypto.randomUUID(), category: "Architecture" },
  { key: crypto.randomUUID(), category: "Business" },
  { key: crypto.randomUUID(), category: "Change" },
  { key: crypto.randomUUID(), category: "Educational" },
  { key: crypto.randomUUID(), category: "Happiness" },
];
